package com.pe.ripley.autorizadornotificacion.model;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Notificacion implements java.io.Serializable {

	static final long serialVersionUID = 1L;


	@org.kie.api.definition.type.Label("Codigo Canal")
	private java.lang.String codCanal;
	
	@org.kie.api.definition.type.Label("Codigo Operacion")
	private java.lang.String codOperacion;
	
	@org.kie.api.definition.type.Label("Monto Transaccion")
	private int montoTransaccion;	
	
	@org.kie.api.definition.type.Label("Codigo Resolucion SIA")
	private java.lang.String codResolSIA;
	
	@org.kie.api.definition.type.Label("Codigo Resolucion Elemento")
	private java.lang.String codResolCodElemento;
	
	@org.kie.api.definition.type.Label("Indicador Autorizacion")
	private java.lang.String indicadorAutorizOperac;
	
	@org.kie.api.definition.type.Label("Estado Operacion SIA")
	private java.lang.String estadoOperacSIA;
	
	@org.kie.api.definition.type.Label("Tipo Tarjeta")
	private java.lang.String tipoTarjeta;
	
	@org.kie.api.definition.type.Label("Codigo de Idenficacion del tipo de mensaje")
	private java.lang.String codIdenTipMsj;
	
	// Asignacion inicial de valores devueltos por la evaluacion de Excel.
	@org.kie.api.definition.type.Label("Ouput Envio Notificacion")
	private java.lang.String ouputEnvioNotif;
	
	@org.kie.api.definition.type.Label("Ouput Tipo Oferta")
	private java.lang.String ouputTipoOferta;
	
	@org.kie.api.definition.type.Label("Ouput Tipo Notificacion")
	private java.lang.String ouputTipoNotificacion;
	
	@org.kie.api.definition.type.Label("ouput Flag Codigo Comercio")
	private java.lang.String ouputFlagCodComercio;
	
	@org.kie.api.definition.type.Label("OuptuFlag Sistema Notificacion")
	private java.lang.String ouputFlagSistemaNotificacion;
	
	@org.kie.api.definition.type.Label("Ouput Flag Oferta Notificacion")
	private java.lang.String ouputFlagOfertaNotificacion;
	
	@org.kie.api.definition.type.Label("Ouput Cantidad Envio x Dia")
	private int ouputCantEnvioXDia;
	
	@org.kie.api.definition.type.Label("Ouput Tipo de Producto")
	private String ouputTipProducto;
	
	@org.kie.api.definition.type.Label("Ouput Identificador de Plantilla de Consumo para SMS")
	private String ouputIdPlantillaConsumoSMS;
	
	@org.kie.api.definition.type.Label("Ouput Identificador de Plantilla de Retiro para SMS")
	private String ouputIdPlantillaRetiroSMS;
	
	@org.kie.api.definition.type.Label("Ouput Identificador de Plantilla de PINMAILER para SMS")
	private String ouputIdPlantillaPinMailerSMS;
	
	@org.kie.api.definition.type.Label("Ouput Identificador de Plantilla de IL para SMS")
	private String ouputIdPlantillaILSMS;
	
	@org.kie.api.definition.type.Label("Ouput Identificador de Plantilla de EFEX para SMS")
	private String ouputIdPlantillaEFEXSMS;
	
	@org.kie.api.definition.type.Label("Ouput Identificador de Plantilla de SEF para SMS")
	private String ouputIdPlantillaSEFSMS;
	
	@org.kie.api.definition.type.Label("Ouput Identificador de Plantilla de Consumo para EMAIL")
	private String ouputIdPlantillaConsumoEmail;
	
	@org.kie.api.definition.type.Label("Ouput Identificador de Plantilla de Retiro para EMAIL")
	private String ouputIdPlantillaRetiroEmail;
	
	@org.kie.api.definition.type.Label("Ouput Identificador de Plantilla de Oferta para EMAIL")
	private String ouputIdPlantillaOfertaEmail;
	
	@org.kie.api.definition.type.Label("Ouput Identificador de Plantilla de PIN para EMAIL")
	private String ouputIdPlantillaPINEmail;
	
	@org.kie.api.definition.type.Label("Ouput Identificador de Plantilla para FISICO")
	private String ouputIdPlantillaFisico;
	
	public Notificacion() {	
	}

	public java.lang.String getCodCanal() {
		return codCanal;
	}

	public void setCodCanal(java.lang.String codCanal) {
		this.codCanal = codCanal;
	}

	public java.lang.String getCodOperacion() {
		return codOperacion;
	}

	public void setCodOperacion(java.lang.String codOperacion) {
		this.codOperacion = codOperacion;
	}

	public int getMontoTransaccion() {
		return montoTransaccion;
	}

	public void setMontoTransaccion(int montoTransaccion) {
		this.montoTransaccion = montoTransaccion;
	}

	public java.lang.String getCodResolSIA() {
		return codResolSIA;
	}

	public void setCodResolSIA(java.lang.String codResolSIA) {
		this.codResolSIA = codResolSIA;
	}

	public java.lang.String getCodResolCodElemento() {
		return codResolCodElemento;
	}

	public void setCodResolCodElemento(java.lang.String codResolCodElemento) {
		this.codResolCodElemento = codResolCodElemento;
	}

	public java.lang.String getIndicadorAutorizOperac() {
		return indicadorAutorizOperac;
	}

	public void setIndicadorAutorizOperac(java.lang.String indicadorAutorizOperac) {
		this.indicadorAutorizOperac = indicadorAutorizOperac;
	}

	public java.lang.String getEstadoOperacSIA() {
		return estadoOperacSIA;
	}

	public void setEstadoOperacSIA(java.lang.String estadoOperacSIA) {
		this.estadoOperacSIA = estadoOperacSIA;
	}

	public java.lang.String getTipoTarjeta() {
		return tipoTarjeta;
	}

	public void setTipoTarjeta(java.lang.String tipoTarjeta) {
		this.tipoTarjeta = tipoTarjeta;
	}

	public java.lang.String getCodIdenTipMsj() {
		return codIdenTipMsj;
	}

	public void setCodIdenTipMsj(java.lang.String codIdenTipMsj) {
		this.codIdenTipMsj = codIdenTipMsj;
	}

	public java.lang.String getOuputEnvioNotif() {
		return ouputEnvioNotif;
	}

	public void setOuputEnvioNotif(java.lang.String ouputEnvioNotif) {
		this.ouputEnvioNotif = ouputEnvioNotif;
	}

	public java.lang.String getOuputTipoOferta() {
		return ouputTipoOferta;
	}

	public void setOuputTipoOferta(java.lang.String ouputTipoOferta) {
		this.ouputTipoOferta = ouputTipoOferta;
	}

	public java.lang.String getOuputTipoNotificacion() {
		return ouputTipoNotificacion;
	}

	public void setOuputTipoNotificacion(java.lang.String ouputTipoNotificacion) {
		this.ouputTipoNotificacion = ouputTipoNotificacion;
	}

	public java.lang.String getOuputFlagCodComercio() {
		return ouputFlagCodComercio;
	}

	public void setOuputFlagCodComercio(java.lang.String ouputFlagCodComercio) {
		this.ouputFlagCodComercio = ouputFlagCodComercio;
	}

	public java.lang.String getOuputFlagSistemaNotificacion() {
		return ouputFlagSistemaNotificacion;
	}

	public void setOuputFlagSistemaNotificacion(java.lang.String ouputFlagSistemaNotificacion) {
		this.ouputFlagSistemaNotificacion = ouputFlagSistemaNotificacion;
	}

	public java.lang.String getOuputFlagOfertaNotificacion() {
		return ouputFlagOfertaNotificacion;
	}

	public void setOuputFlagOfertaNotificacion(java.lang.String ouputFlagOfertaNotificacion) {
		this.ouputFlagOfertaNotificacion = ouputFlagOfertaNotificacion;
	}

	public int getOuputCantEnvioXDia() {
		return ouputCantEnvioXDia;
	}

	public void setOuputCantEnvioXDia(int ouputCantEnvioXDia) {
		this.ouputCantEnvioXDia = ouputCantEnvioXDia;
	}
	
	public java.lang.String getOuputTipProducto() {
		return ouputTipProducto;
	}

	public void setOuputTipProducto(java.lang.String ouputTipProducto) {
		this.ouputTipProducto = ouputTipProducto;
	}

	public java.lang.String getOuputIdPlantillaConsumoSMS() {
		return ouputIdPlantillaConsumoSMS;
	}

	public void setOuputIdPlantillaConsumoSMS(java.lang.String ouputIdPlantillaConsumoSMS) {
		this.ouputIdPlantillaConsumoSMS = ouputIdPlantillaConsumoSMS;
	}

	public java.lang.String getOuputIdPlantillaRetiroSMS() {
		return ouputIdPlantillaRetiroSMS;
	}

	public void setOuputIdPlantillaRetiroSMS(java.lang.String ouputIdPlantillaRetiroSMS) {
		this.ouputIdPlantillaRetiroSMS = ouputIdPlantillaRetiroSMS;
	}

	public java.lang.String getOuputIdPlantillaPinMailerSMS() {
		return ouputIdPlantillaPinMailerSMS;
	}

	public void setOuputIdPlantillaPinMailerSMS(java.lang.String ouputIdPlantillaPinMailerSMS) {
		this.ouputIdPlantillaPinMailerSMS = ouputIdPlantillaPinMailerSMS;
	}

	public java.lang.String getOuputIdPlantillaILSMS() {
		return ouputIdPlantillaILSMS;
	}

	public void setOuputIdPlantillaILSMS(java.lang.String ouputIdPlantillaILSMS) {
		this.ouputIdPlantillaILSMS = ouputIdPlantillaILSMS;
	}

	public java.lang.String getOuputIdPlantillaEFEXSMS() {
		return ouputIdPlantillaEFEXSMS;
	}

	public void setOuputIdPlantillaEFEXSMS(java.lang.String ouputIdPlantillaEFEXSMS) {
		this.ouputIdPlantillaEFEXSMS = ouputIdPlantillaEFEXSMS;
	}

	public java.lang.String getOuputIdPlantillaSEFSMS() {
		return ouputIdPlantillaSEFSMS;
	}

	public void setOuputIdPlantillaSEFSMS(java.lang.String ouputIdPlantillaSEFSMS) {
		this.ouputIdPlantillaSEFSMS = ouputIdPlantillaSEFSMS;
	}

	public java.lang.String getOuputIdPlantillaConsumoEmail() {
		return ouputIdPlantillaConsumoEmail;
	}

	public void setOuputIdPlantillaConsumoEmail(java.lang.String ouputIdPlantillaConsumoEmail) {
		this.ouputIdPlantillaConsumoEmail = ouputIdPlantillaConsumoEmail;
	}

	public java.lang.String getOuputIdPlantillaRetiroEmail() {
		return ouputIdPlantillaRetiroEmail;
	}

	public void setOuputIdPlantillaRetiroEmail(java.lang.String ouputIdPlantillaRetiroEmail) {
		this.ouputIdPlantillaRetiroEmail = ouputIdPlantillaRetiroEmail;
	}

	public java.lang.String getOuputIdPlantillaOfertaEmail() {
		return ouputIdPlantillaOfertaEmail;
	}

	public void setOuputIdPlantillaOfertaEmail(java.lang.String ouputIdPlantillaOfertaEmail) {
		this.ouputIdPlantillaOfertaEmail = ouputIdPlantillaOfertaEmail;
	}

	public java.lang.String getOuputIdPlantillaPINEmail() {
		return ouputIdPlantillaPINEmail;
	}

	public void setOuputIdPlantillaPINEmail(java.lang.String ouputIdPlantillaPINEmail) {
		this.ouputIdPlantillaPINEmail = ouputIdPlantillaPINEmail;
	}

	public java.lang.String getOuputIdPlantillaFisico() {
		return ouputIdPlantillaFisico;
	}

	public void setOuputIdPlantillaFisico(java.lang.String ouputIdPlantillaFisico) {
		this.ouputIdPlantillaFisico = ouputIdPlantillaFisico;
	}

	public Notificacion(java.lang.String codCanal, java.lang.String codOperacion, int montoTransaccion, java.lang.String codResolSIA,
			java.lang.String codResolCodElemento, java.lang.String indicadorAutorizOperac, java.lang.String estadoOperacSIA, java.lang.String tipoTarjeta,
			java.lang.String codIdenTipMsj, java.lang.String ouputEnvioNotif, java.lang.String ouputTipoOferta, java.lang.String ouputTipoNotificacion,
			java.lang.String ouputFlagCodComercio, java.lang.String ouputFlagSistemaNotificacion, java.lang.String ouputFlagOfertaNotificacion,
			int ouputCantEnvioXDia, java.lang.String ouputTipProducto, java.lang.String ouputIdPlantillaConsumoSMS,
			java.lang.String ouputIdPlantillaRetiroSMS, java.lang.String ouputIdPlantillaPinMailerSMS, java.lang.String ouputIdPlantillaILSMS,
			java.lang.String ouputIdPlantillaEFEXSMS, java.lang.String ouputIdPlantillaSEFSMS, java.lang.String ouputIdPlantillaConsumoEmail,
			java.lang.String ouputIdPlantillaRetiroEmail, java.lang.String ouputIdPlantillaOfertaEmail, java.lang.String ouputIdPlantillaPINEmail,
			java.lang.String ouputIdPlantillaFisico) {

		this.codCanal = codCanal;
		this.codOperacion = codOperacion;
		this.montoTransaccion = montoTransaccion;
		this.codResolSIA = codResolSIA;
		this.codResolCodElemento = codResolCodElemento;
		this.indicadorAutorizOperac = indicadorAutorizOperac;
		this.estadoOperacSIA = estadoOperacSIA;
		this.tipoTarjeta = tipoTarjeta;
		this.codIdenTipMsj = codIdenTipMsj;
		this.ouputEnvioNotif = ouputEnvioNotif;
		this.ouputTipoOferta = ouputTipoOferta;
		this.ouputTipoNotificacion = ouputTipoNotificacion;
		this.ouputFlagCodComercio = ouputFlagCodComercio;
		this.ouputFlagSistemaNotificacion = ouputFlagSistemaNotificacion;
		this.ouputFlagOfertaNotificacion = ouputFlagOfertaNotificacion;
		this.ouputCantEnvioXDia = ouputCantEnvioXDia;
		this.ouputTipProducto = ouputTipProducto;
		this.ouputIdPlantillaConsumoSMS = ouputIdPlantillaConsumoSMS;
		this.ouputIdPlantillaRetiroSMS = ouputIdPlantillaRetiroSMS;
		this.ouputIdPlantillaPinMailerSMS = ouputIdPlantillaPinMailerSMS;
		this.ouputIdPlantillaILSMS = ouputIdPlantillaILSMS;
		this.ouputIdPlantillaEFEXSMS = ouputIdPlantillaEFEXSMS;
		this.ouputIdPlantillaSEFSMS = ouputIdPlantillaSEFSMS;
		this.ouputIdPlantillaConsumoEmail = ouputIdPlantillaConsumoEmail;
		this.ouputIdPlantillaRetiroEmail = ouputIdPlantillaRetiroEmail;
		this.ouputIdPlantillaOfertaEmail = ouputIdPlantillaOfertaEmail;
		this.ouputIdPlantillaPINEmail = ouputIdPlantillaPINEmail;
		this.ouputIdPlantillaFisico = ouputIdPlantillaFisico;
	}	
	
}