package com.pe.ripley.autorizadornotificacion.model;

import java.math.BigInteger;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class ResponseNotificacion implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("Envio Notificacion")
	private java.lang.String envioNotif;
	
	@org.kie.api.definition.type.Label("Tipo Oferta")
	private java.lang.String tipoOferta;
	
	@org.kie.api.definition.type.Label("Tipo Notificacion")
	private java.lang.String tipoNotificacion;
	
	@org.kie.api.definition.type.Label("Flag Codigo Comercio")
	private java.lang.String flagCodComercio;
	
	@org.kie.api.definition.type.Label("Flag Sistema Notificacion")
	private java.lang.String flagSistemaNotificacion;
	
	@org.kie.api.definition.type.Label("Flag Oferta Notificacion")
	private java.lang.String flagOfertaNotificacion;
	
	@org.kie.api.definition.type.Label("Cantidad Envio x Dia")
	private int cantEnvioXDia;
	
	@org.kie.api.definition.type.Label("Tipo de Producto")
	private String tipProducto;
	
	@org.kie.api.definition.type.Label("Identificador de Plantilla de Consumo para SMS")
	private String idPlantillaConsumoSMS;
	
	@org.kie.api.definition.type.Label("Identificador de Plantilla de Retiro para SMS")
	private String idPlantillaRetiroSMS;
	
	@org.kie.api.definition.type.Label("Identificador de Plantilla de PINMAILER para SMS")
	private String idPlantillaPinMailerSMS;
	
	@org.kie.api.definition.type.Label("Identificador de Plantilla de IL para SMS")
	private String idPlantillaILSMS;
	
	@org.kie.api.definition.type.Label("Identificador de Plantilla de EFEX para SMS")
	private String idPlantillaEFEXSMS;
	
	@org.kie.api.definition.type.Label("Identificador de Plantilla de SEF para SMS")
	private String idPlantillaSEFSMS;
	
	@org.kie.api.definition.type.Label("Identificador de Plantilla de Consumo para EMAIL")
	private String idPlantillaConsumoEmail;
	
	@org.kie.api.definition.type.Label("Identificador de Plantilla de Retiro para EMAIL")
	private String idPlantillaRetiroEmail;
	
	@org.kie.api.definition.type.Label("Identificador de Plantilla de Oferta para EMAIL")
	private String idPlantillaOfertaEmail;
	
	@org.kie.api.definition.type.Label("Identificador de Plantilla de PIN para EMAIL")
	private String idPlantillaPINEmail;
	
	@org.kie.api.definition.type.Label("Identificador de Plantilla para FISICO")
	private String idPlantillaFisico;

	public ResponseNotificacion() {		
	}
	
	public java.lang.String getEnvioNotif() {
		return envioNotif;
	}

	public void setEnvioNotif(java.lang.String envioNotif) {
		this.envioNotif = envioNotif;
	}

	public java.lang.String getTipoOferta() {
		return tipoOferta;
	}

	public void setTipoOferta(java.lang.String tipoOferta) {
		this.tipoOferta = tipoOferta;
	}

	public java.lang.String getTipoNotificacion() {
		return tipoNotificacion;
	}

	public void setTipoNotificacion(java.lang.String tipoNotificacion) {
		this.tipoNotificacion = tipoNotificacion;
	}

	public java.lang.String getFlagCodComercio() {
		return flagCodComercio;
	}

	public void setFlagCodComercio(java.lang.String flagCodComercio) {
		this.flagCodComercio = flagCodComercio;
	}

	public java.lang.String getFlagSistemaNotificacion() {
		return flagSistemaNotificacion;
	}

	public void setFlagSistemaNotificacion(java.lang.String flagSistemaNotificacion) {
		this.flagSistemaNotificacion = flagSistemaNotificacion;
	}

	public java.lang.String getFlagOfertaNotificacion() {
		return flagOfertaNotificacion;
	}

	public void setFlagOfertaNotificacion(java.lang.String flagOfertaNotificacion) {
		this.flagOfertaNotificacion = flagOfertaNotificacion;
	}

	public int getCantEnvioXDia() {
		return cantEnvioXDia;
	}

	public void setCantEnvioXDia(int cantEnvioXDia) {
		this.cantEnvioXDia = cantEnvioXDia;
	}

	public java.lang.String getTipProducto() {
		return tipProducto;
	}

	public void setTipProducto(java.lang.String tipProducto) {
		this.tipProducto = tipProducto;
	}

	public java.lang.String getIdPlantillaConsumoSMS() {
		return idPlantillaConsumoSMS;
	}

	public void setIdPlantillaConsumoSMS(java.lang.String idPlantillaConsumoSMS) {
		this.idPlantillaConsumoSMS = idPlantillaConsumoSMS;
	}

	public java.lang.String getIdPlantillaRetiroSMS() {
		return idPlantillaRetiroSMS;
	}

	public void setIdPlantillaRetiroSMS(java.lang.String idPlantillaRetiroSMS) {
		this.idPlantillaRetiroSMS = idPlantillaRetiroSMS;
	}

	public java.lang.String getIdPlantillaPinMailerSMS() {
		return idPlantillaPinMailerSMS;
	}

	public void setIdPlantillaPinMailerSMS(java.lang.String idPlantillaPinMailerSMS) {
		this.idPlantillaPinMailerSMS = idPlantillaPinMailerSMS;
	}

	public java.lang.String getIdPlantillaILSMS() {
		return idPlantillaILSMS;
	}

	public void setIdPlantillaILSMS(java.lang.String idPlantillaILSMS) {
		this.idPlantillaILSMS = idPlantillaILSMS;
	}

	public java.lang.String getIdPlantillaEFEXSMS() {
		return idPlantillaEFEXSMS;
	}

	public void setIdPlantillaEFEXSMS(java.lang.String idPlantillaEFEXSMS) {
		this.idPlantillaEFEXSMS = idPlantillaEFEXSMS;
	}

	public java.lang.String getIdPlantillaSEFSMS() {
		return idPlantillaSEFSMS;
	}

	public void setIdPlantillaSEFSMS(java.lang.String idPlantillaSEFSMS) {
		this.idPlantillaSEFSMS = idPlantillaSEFSMS;
	}

	public java.lang.String getIdPlantillaConsumoEmail() {
		return idPlantillaConsumoEmail;
	}

	public void setIdPlantillaConsumoEmail(java.lang.String idPlantillaConsumoEmail) {
		this.idPlantillaConsumoEmail = idPlantillaConsumoEmail;
	}

	public java.lang.String getIdPlantillaRetiroEmail() {
		return idPlantillaRetiroEmail;
	}

	public void setIdPlantillaRetiroEmail(java.lang.String idPlantillaRetiroEmail) {
		this.idPlantillaRetiroEmail = idPlantillaRetiroEmail;
	}

	public java.lang.String getIdPlantillaOfertaEmail() {
		return idPlantillaOfertaEmail;
	}

	public void setIdPlantillaOfertaEmail(java.lang.String idPlantillaOfertaEmail) {
		this.idPlantillaOfertaEmail = idPlantillaOfertaEmail;
	}

	public java.lang.String getIdPlantillaPINEmail() {
		return idPlantillaPINEmail;
	}

	public void setIdPlantillaPINEmail(java.lang.String idPlantillaPINEmail) {
		this.idPlantillaPINEmail = idPlantillaPINEmail;
	}

	public java.lang.String getIdPlantillaFisico() {
		return idPlantillaFisico;
	}

	public void setIdPlantillaFisico(java.lang.String idPlantillaFisico) {
		this.idPlantillaFisico = idPlantillaFisico;
	}

	public ResponseNotificacion(java.lang.String envioNotif, java.lang.String tipoOferta, java.lang.String tipoNotificacion, java.lang.String flagCodComercio,
			java.lang.String flagSistemaNotificacion, java.lang.String flagOfertaNotificacion, int cantEnvioXDia, java.lang.String tipProducto,
			java.lang.String idPlantillaConsumoSMS, java.lang.String idPlantillaRetiroSMS, java.lang.String idPlantillaPinMailerSMS,
			java.lang.String idPlantillaILSMS, java.lang.String idPlantillaEFEXSMS, java.lang.String idPlantillaSEFSMS,
			java.lang.String idPlantillaConsumoEmail, java.lang.String idPlantillaRetiroEmail, java.lang.String idPlantillaOfertaEmail,
			java.lang.String idPlantillaPINEmail, java.lang.String idPlantillaFisico) {
		
		this.envioNotif = envioNotif;
		this.tipoOferta = tipoOferta;
		this.tipoNotificacion = tipoNotificacion;
		this.flagCodComercio = flagCodComercio;
		this.flagSistemaNotificacion = flagSistemaNotificacion;
		this.flagOfertaNotificacion = flagOfertaNotificacion;
		this.cantEnvioXDia = cantEnvioXDia;
		this.tipProducto = tipProducto;
		this.idPlantillaConsumoSMS = idPlantillaConsumoSMS;
		this.idPlantillaRetiroSMS = idPlantillaRetiroSMS;
		this.idPlantillaPinMailerSMS = idPlantillaPinMailerSMS;
		this.idPlantillaILSMS = idPlantillaILSMS;
		this.idPlantillaEFEXSMS = idPlantillaEFEXSMS;
		this.idPlantillaSEFSMS = idPlantillaSEFSMS;
		this.idPlantillaConsumoEmail = idPlantillaConsumoEmail;
		this.idPlantillaRetiroEmail = idPlantillaRetiroEmail;
		this.idPlantillaOfertaEmail = idPlantillaOfertaEmail;
		this.idPlantillaPINEmail = idPlantillaPINEmail;
		this.idPlantillaFisico = idPlantillaFisico;
	}

}